[project]
name = "finetuneeditor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langsmith>=0.4.20",
    "numpy>=2.2.6",
    "openai>=1.102.0",
    "scikit-learn>=1.7.1",
]
